## Python Basics

This is a markdown cell in Jupyter notebook. This is a basics to python notebook.

In [10]:
# This is a comment in Python.

In [13]:
# printing in python
print("Hello, World!")
print("hello")
print("----")

Hello, World!
hello
----


In [19]:
# Create new variables.
x = 354
y = "customers"

# Print a variable.
print(x)
print(x, y)

# type(x)
type(5.0)
type(y)

print(str(x) + y) # will generate an error.  (Different types.)

354
354 customers
354customers


In [ ]:
# common data types
a = "butterbeer"                    # string
b = 5                               # integer
c = 5.5                             # float
d = ["harry", "ron", "voldemort"]   # list
e = {"name" : "harry", "age" : 15}  # dictionary
f = True                          # boolean

In [29]:
type(False)

bool

In [33]:
# Specify data types
x = int(15)  # x is an integer (15)
y = str(15)  # x is a string ("15")

# Check the variable type.
print(type(x))
print(type(y))

print(str(x) + " " + y)
# Variables are case-sensitive: x is not X
# Variables are easy to read with snake case: total_customers

<class 'int'>
<class 'str'>
15 15


In [55]:
# Experiment with strings
z = "neural networks"

print(z)                      # print the string         
print(z[1])                   # print the second character
print(len(z))                 # print the number of characters
print(z.upper())              # print an uppercase version
print(z.replace("net", "works"))   # print and replace "net" with "works"
print(z.isnumeric())          # print whether z is numeric
print("works" in z)            # print whether "works" is in z

neural networks
e
15
NEURAL NETWORKS
neural worksworks
False
True


In [58]:
print("l net" in z)

True


In [59]:
# Try different operators
print(10 + 5)   # addition
print(10 - 5)   # subtraction
print(10 * 5)   # multiplication
print(10 / 5)   # division
print(10 ** 5)  # exponents

# Explore a few built-in math functions.
print(min(100, 50))
print(max(100, 50))

15
5
50
2.0
100000
50
100


In [65]:
# Experiment with booleans and comparisons.
print(100 >= 50)
print(100 == 50)
print(100 != 50)
print("harry" == "hermoine")

True
False
True
False


In [69]:
print("harry " == "harry ")

True


In [70]:
# Use indentation for a block of code
if 25 < 50:
  print("true")

true


In [72]:
# Use indentation for a block of code
if 51 < 50:
    print("true")
else:
    print("false")

false


In [77]:
# for loop example
for i in range(5):
    print("Iteration:", i)
    # print(i)
    print(i ** 2)
    print(i / 2)

Iteration: 0
0
0.0
Iteration: 1
1
0.5
Iteration: 2
4
1.0
Iteration: 3
9
1.5
Iteration: 4
16
2.0


In [73]:
range(5)

range(0, 5)

In [ ]:
z = "neural networks"

for i in z:
    print("Character:", i)
    print(i)


    

Character: n
n
Character: e
e
Character: u
u
Character: r
r
Character: a
a
Character: l
l
Character:  
 
Character: n
n
Character: e
e
Character: t
t
Character: w
w
Character: o
o
Character: r
r
Character: k
k
Character: s
s


In [97]:
lst = [1, 2, 3, 4, 5]
weights = [0.1, 0.2, 0.3, 0.4, 0.5]

for weight in weights:
    print(w)

0.5
0.5
0.5
0.5
0.5


In [88]:
# Import a Python library
import numpy as np

# np.arange(5)

# Use the Python library
numbers = np.arange(2, 7)         # Create a NumPy array
print(numbers)
type(numbers)                    # Print the array

[2 3 4 5 6]


numpy.ndarray

In [83]:
max(lst)                       # Find the maximum value in the array

5

In [85]:
np.max(lst)                  # Find the maximum value in the array

5

In [92]:
np.array([1, 2, 3, 4,5,6,7,8])  # Create a NumPy array from a list

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
# create a matrix from numpy
list_matrix_array = [[2, 3],
                      [4, 5],
                      [6, 7]]

np.array(list_matrix_array)
# Check the shape of the matrix
print(np.array(list_matrix_array).shape) 
print("----")
print(np.array(list_matrix_array))

(3, 2)
----
[[2 3]
 [4 5]
 [6 7]]


In [90]:
list_matrix_array

[[2, 3], [4, 5], [6, 7]]